### ISSUE TITLE
the extension requests the "Access your data for all websites" permission

### ISSUE THREAD

**Issue by jjanuszkiewicz** [ethanliu/location-switcher-addon#13]
I have Location Switcher version 1.3.0 in Firefox. Now FF tries to update it, but the new version requests the "Access your data for all websites" permission, which [is described](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct#w_access-your-data-for-all-websites) as:

> The extension can read the content of any web page you visit as well as data you enter into those web pages, such as usernames and passwords. 

Why does the new version request such extensive permissions? I think it is not justified.

**Comment by ethanliu** [comment]
the latest version add replace favicon that needs inject scripts to the page by browser.tabs.executeScript that require activeTab permission. however it actually needs <all_urls> permission to make it work. 

Maybe there is a more properly permission option for this.

**Comment by pavlitsky** [comment]
@ethanliu I, too, think that the favicon feature isn't worth such a permissions escalation. It would be great if you find a way to revert this.

**Comment by ethanliu** [comment]
I agree all the concerns.

@MurzNN and since there is no way to run content scripts without <all_urls> host permission for this purpose. This feature may have to remove.

**Comment by MurzNN** [comment]
@ethanliu Maybe make this feature as separate "extended" extension, or little companion to main extension?

**Comment by MurzNN** [comment]
And also I don't see any problems, that opensource extension will have access to all websites. A lot of extensions, that works with current tab, asks this permission.

**Comment by jenoe** [comment]
opensource or not: this is a no-go for me. I uninstalled the extension and will not reinstall it unless the permissions will be downgraded again.

**Comment by MurzNN** [comment]
So best solution will be publish two versions of extension:
- Location Switcher
- Location Switcher with Favicon

@ethanliu Is it hard to make and support two similar versions of one extension?

**Comment by ethanliu** [comment]
giving up permissions is not just for one release, it means all future releases have the same permissions unless you completely trust the author or really pay attention to the source, even so, the uploaded extension package doesn't guarantee using the same code.

I think its why most people include me, don't feel comfortable for giving up such permission for a 3rd party extension.

Since the permissions request is defined in manifest.json, you can only have one requirement for one extension.

Separate into two versions or self-hosting builds might be the only solution.
